# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jez Humble's Personal Blog
email: humble@acm.org
description: > # this means to ignore newlines until "baseurl:"
  Jez Humble's Personal Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jezhumble.net" # the base hostname & protocol for your site
twitter_username: jezhumble
github_username:  jezhumble
encoding: utf-8
highlighter: rouge
incremental: true

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo